sms_gateway_settings_extended:
  type: sms_gateway_settings
  label: 'Extended SMS Gateway settings'
  mapping:
    ssl:
      type: boolean
      label: 'Whether to enable SSL or not for this gateway.'
    server:
      type: string
      label: 'The domain name of the gateway server.'
    port:
      type: string
      label: 'The port number to connect to the server HTTP API.'
    username:
      type: string
      label: 'The username for logging into the gateway.'
    password:
      type: string
      label: 'The password for logging into the gateway.'
    method:
      type: string
      label: 'The method'
    reports:
      type: boolean
      label: 'Whether delivery reports should be pushed after message sending.'
    no_validate:
      type: boolean
      label: 'Whether or not to validate the settings before accepting them.'
