sms_gateway.settings.infobip:
  type: sms_gateway_settings_extended
  label: 'Infobip'
  mapping: { }

sms_gateway.settings.routesms:
  type: sms_gateway_settings_extended
  label: 'RouteSMS'
  mapping:
    test_number:
      type: string
      label: 'Test number'
